# Generated by Django 4.1.7 on 2023-05-01 09:18

from django.db import migrations, models
import django_mysql.models
import question.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_delete_testinglistfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testinglistfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', question.fields.ListField(token=',')),
                ('content', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('tests', django_mysql.models.ListCharField(models.IntegerField(), blank=True, default=None, max_length=66, null=True, size=6)),
            ],
        ),
    ]
