# Generated by Django 4.1.7 on 2023-05-01 09:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_testinglistfield_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testinglistfield1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chars', django_mysql.models.ListCharField(models.IntegerField(), blank=True, default=None, max_length=66, null=True, size=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Testinglistfield',
        ),
    ]
