# Generated by Django 4.1.7 on 2023-05-01 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_testinglistfield1_delete_testinglistfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinglistfield1',
            name='question_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='qsn3456', to='question.testingpurpose'),
        ),
        migrations.AddField(
            model_name='testinglistfield1',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nothing45', to=settings.AUTH_USER_MODEL),
        ),
    ]
