# Generated by Django 4.1.7 on 2023-05-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_testinglistfield1_question_no_testinglistfield1_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinglistfield1',
            name='question_no',
        ),
        migrations.RemoveField(
            model_name='testinglistfield1',
            name='user',
        ),
    ]
