# Generated by Django 4.1.7 on 2023-05-01 10:22

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_remove_testinglistfield1_question_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinglistfield1',
            name='extra_info',
            field=picklefield.fields.PickledObjectField(default=None, editable=False),
        ),
    ]
