# Generated by Django 4.1.7 on 2023-05-01 10:24

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_testinglistfield1_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinglistfield1',
            name='extra_info',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
    ]
