# Generated by Django 4.1.7 on 2023-05-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_alter_testinglistfield1_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinglistfield1',
            name='extra_info',
            field=models.JSONField(default=dict),
        ),
    ]
