# Generated by Django 4.1.7 on 2023-05-02 04:11

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_alter_testinglistfield1_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinglistfield1',
            name='extra_info',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
