# Generated by Django 4.1.7 on 2023-05-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_alter_testinglistfield1_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinglistfield1',
            name='left_info',
            field=models.JSONField(default=dict),
        ),
    ]
