# Generated by Django 4.1.7 on 2023-05-02 04:57

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_testinglistfield1_left_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinglistfield1',
            name='lstoflst',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='testingattemptquestion',
            name='question_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='qsn3', to='question.testingpurpose', verbose_name='attempt_question'),
        ),
    ]
