# Generated by Django 4.1.7 on 2023-05-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_testinglistfield1_lstoflst_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinglistfield1',
            options={'verbose_name': 'TestingModel'},
        ),
    ]
