# Generated by Django 4.1.7 on 2023-05-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_alter_testinglistfield1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinglistfield1',
            options={'verbose_name': 'TestingModel', 'verbose_name_plural': '11. TestingModel'},
        ),
    ]
