# Generated by Django 4.1.7 on 2023-05-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_alter_testinglistfield1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestion',
            options={'verbose_name_plural': 'AnswerQuestions'},
        ),
        migrations.AlterModelOptions(
            name='answerquizquestion',
            options={'verbose_name_plural': 'AnswerQuizQuestions'},
        ),
        migrations.AlterModelOptions(
            name='contenders',
            options={'verbose_name_plural': 'Contenders'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizanswerssheet',
            options={'verbose_name_plural': 'QuizAnswersSheet'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': 'QuizQuestions'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name_plural': 'Rankings of candidates'},
        ),
        migrations.AlterModelOptions(
            name='scoreofcandidate',
            options={'verbose_name_plural': 'ScoreofCandidates'},
        ),
        migrations.AlterModelOptions(
            name='tempquiz',
            options={'verbose_name_plural': 'TempQuiz'},
        ),
        migrations.AlterModelOptions(
            name='tempquizanswer',
            options={'verbose_name_plural': 'TempQuizAnswer'},
        ),
        migrations.AlterModelOptions(
            name='tempscoreofcandidate',
            options={'verbose_name_plural': 'TempScoreofCandidate'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
