# Generated by Django 4.1.7 on 2023-05-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0021_user_username_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinglistfield1',
            name='lstoflst',
        ),
    ]
