# Generated by Django 4.1.7 on 2023-05-03 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0023_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mainuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
