from . import views
from django.urls import path
from .views import *
urlpatterns = [
    path('api/login/', loginAPI.as_view()),
    path('api/signup/', SignupView.as_view()),
    path('api/question/', AddQuestion.as_view()),
    path('api/answering/', AttemptAnswer.as_view()),
    path('api/allquestion/', DisplayAllQuestions.as_view()),
    path('api/allanswer/', DisplayAllAnswers.as_view()),
    path('api/alluser/', DisplayAllUsers.as_view()),
    path('api/editdeletequestion/<int:id>/', EditDeleteQuestion.as_view()),
    path('api/quizquestion/', AddQuizQuestion.as_view()),
    path('api/allquizquestion/', DisplayAllQuizQuestions.as_view()),
    path('api/quizanswer/', AddQuizAnswers.as_view()),
    path('api/displayquizanswers/', DisplayQuizSheetAnswers.as_view()),
    path('api/quizanswering/', UserAttemptQuizAnswer.as_view()),
    path('api/showallusers/', ShowAllUsers.as_view()),
    path('api/allquizanswer/', ShowAllQuizAnswers.as_view()),
    path('api/showmarks/', CalculateMarks.as_view()),
    path('api/userquizanswers/<int:id>/', UserQuizAnswers.as_view()),
    path('api/scoresofcandidates/', ScoresOfCandidates.as_view()),
    path('api/ranking/', RankingsofCandidate.as_view()),
    path('api/templquiz/', TemplQuizQuestions.as_view(), name="quiz"),
    path('api/detailsforquiz/', EnterDetails.as_view(), name="details"),
    path('attemptquiz/<int:id>/', TempAttemptQuiz.as_view(), name="attempt_quiz"),
    path('displayscores/', DisplayScores.as_view(), name="scoresdisplay"),
    path('api/testingquestion/', TestingAddQuestion.as_view()),
    path('api/testingattemptquestion/', TestingAttemptAnswer.as_view()),
    path('api/testingeditdeletequestion/<int:id>/', TestingEditQuestion.as_view()),
    path('api/testingdisplayallquestions/', TestingDisplayAllQuestions.as_view()),
    path('api/testingdisplayallanswers/<int:id>/', DisplayAnswersOfUser.as_view()),
    path('api/testingquizquestion/', AddTestingQuizQuestion.as_view()),
    path('api/displayalltestingquizquestions/', AllTestingQuizQuestions.as_view()),
    path('api/items/', AddItems.as_view()),
    path('api/allitems/', AllListItems.as_view()),
    path('api/addfriend(s)/', AddFriends.as_view()),

]