# Generated by Django 4.1.7 on 2023-04-18 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_purchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_of_user',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'normal_user')], default='1', max_length=255),
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
