# Generated by Django 4.1.7 on 2023-04-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_user_role_of_user_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lucky_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
