# Generated by Django 4.1.7 on 2023-04-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_blog_lucky_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
